vim.opt.autowrite      = true
vim.opt.backup         = false
vim.opt.breakindent    = true
vim.opt.clipboard      = 'unnamedplus'
vim.opt.completeopt    = 'menu,menuone,noselect,popup'
vim.opt.directory      = '/tmp'
vim.opt.expandtab      = true
vim.opt.exrc           = true
vim.opt.fillchars:append({ vert = '│' })
vim.opt.fixendofline   = true
vim.opt.foldenable     = false
vim.opt.foldmethod     = 'manual'
vim.opt.formatoptions:append('j')
vim.opt.guicursor      = ''
vim.opt.history        = 10000
vim.opt.ignorecase     = true
vim.opt.joinspaces     = false
vim.opt.laststatus     = 3
vim.opt.list           = true
vim.opt.listchars      = { extends = '❯', nbsp = '⋅', precedes = '❮', space = '⋅', tab = '▸ ', trail = '⋅' }
vim.opt.number         = true
vim.opt.numberwidth    = 2
vim.opt.pumheight      = 10
vim.opt.relativenumber = true
vim.opt.scrolloff      = 10
vim.opt.shiftwidth     = 4
vim.opt.shortmess:append('cI')
vim.opt.showbreak      = '↳ '
vim.opt.signcolumn     = 'number'
vim.opt.smartcase      = true
vim.opt.smartindent    = true
vim.opt.softtabstop    = 4
vim.opt.swapfile       = false
vim.opt.tabstop        = 4
vim.opt.textwidth      = 79
vim.opt.timeoutlen     = 500
vim.opt.title          = true
vim.opt.titleold       = ''
vim.opt.titlestring    = 'nvim: %F'
vim.opt.undodir        = vim.fn.stdpath('cache') .. '/undo'
vim.opt.undofile       = true
vim.opt.undolevels     = 100
vim.opt.undoreload     = 10000
vim.opt.updatetime     = 300
vim.opt.virtualedit    = 'block'
vim.opt.wildmode       = 'longest,list'
vim.opt.wrap           = false
vim.opt.writebackup    = false
